controllers/EventController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Event;
use app\models\EventSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;


/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (!\Yii::$app->user->can('indexActivity'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to see events');

      $events = Event::find()->all();
        
      $tasks=[];  
      foreach ($events AS $eve){
      //Testing
      $event = new \yii2fullcalendar\models\Event();
      $event->id = $eve->eventId;
      $event->backgroundColor='#008B8B' ;
      $event->title = $eve->title;
      $event->start = $eve->date; 
    //  $event->start = date('Y-m-d\Th:m:s\Z',strtotime('6am'));
      $tasks[] = $event;
    }
        
        return $this->render('index', [
            'events' => $tasks,
            ]);
        
    }
    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
         if (!\Yii::$app->user->can('createEvent'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to create events');
        $model = new Event();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->eventId]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
         if (!\Yii::$app->user->can('updateEvent'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to update event');
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->eventId]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
         if (!\Yii::$app->user->can('deleteEvent'))
        throw new UnauthorizedHttpException ('Hey, You are not allowed to delete event');
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Event::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/TeamController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Team;
use app\models\TeamSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\growl\Growl;
use yii\web\UnauthorizedHttpException;
use app\models\User;



/**
 * TeamController implements the CRUD actions for Team model.
 */
class TeamController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Team models.
     * @return mixed
     */
    public function actionIndex()
    {
              if (!\Yii::$app->user->can('indexTeams'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to see teams');
        $searchModel = new TeamSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider, 
                'ids' => Team::getcoord(),
    			'id' => $searchModel->id,
                'guides' => Team::getguide(),
    			'guide' => $searchModel->id,
          


        ]);
    }


    /**
     * Displays a single Team model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {

//         echo Growl::widget([
//     'type' => Growl::TYPE_SUCCESS,
//     'icon' => 'glyphicon glyphicon-ok-sign',
//     'title' => 'Note',
//     'showSeparator' => true,
//     'body' => 'great! you have  just ceated a new team'
// ]);

 if (!\Yii::$app->user->can('indexTeams'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to see teams');
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Team model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (!\Yii::$app->user->can('deleteUser'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to create teams');
        $model = new Team();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->teamNumber]);
        } else {

            return $this->render('create', [
                'model' => $model,
         
             


            

            ]);
        }
    }

    /**
     * Updates an existing Team model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (!\Yii::$app->user->can('deleteUser'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to update teams');
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->teamNumber]);
        } else {
                 return $this->render('update', [
                    'model' => $model,
              
                 

            ]);
        }
    }

    /**
     * Deletes an existing Team model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (!\Yii::$app->user->can('deleteUser'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to delete teams');
        
        $this->findModel($id)->delete();
          
        return $this->redirect(['index']);
    }

    /**
     * Finds the Team model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Team the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Team::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\userSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;
use kartik\alert\AlertBlock;
use kartik\growl\Growl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (!\Yii::$app->user->can('indexUser'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to see users');
        $searchModel = new userSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
                'roles' => User::getRolesWithAllRoles(),
                'role' => $searchModel->role,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
// echo Growl::widget([
//     'type' => Growl::TYPE_SUCCESS,
//     'icon' => 'glyphicon glyphicon-ok-sign',
//     'title' => 'Note',
//     'showSeparator' => true,
//     'body' => 'you have successfully created a new user'
// ]);
    
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
     public function actionCreate()
    {
       //access control
     if (!\Yii::$app->user->can('createUser'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to create new users');
        $model = new User();
        

// echo Growl::widget([
//     'type' => Growl::TYPE_WARNING,
//     'icon' => 'glyphicon glyphicon-ok-sign',
//     'title' => 'Note',
//     'showSeparator' => true,
//     'body' => 'please notice! spacify the right role'
// ]);


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $roles = User::getRoles(); 
            return $this->render('create', [
                'model' => $model,
                'roles' => $roles,

            ]);
        


        }
    }
    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if (!\Yii::$app->user->can('updateUser'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to create new users');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $roles = User::getRoles(); 
            return $this->render('update', [
                'model' => $model,
                'roles' => $roles,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (!\Yii::$app->user->can('deleteUser'))
            throw new UnauthorizedHttpException ('Hey, You are not allowed to delete users');
        
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            $roles = \Yii::$app->authManager->getRolesByUser($model->id);
            $model->role = array_keys($roles)[0];
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\user;

//use app\assets\AdminAsset;


AppAsset::register($this);
//AdminAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
     //   'brandLabel' => '<img src = "images/sky.png ">',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
          // !Yii::$app->user->isGuest ?
          //   ['label' => 'Home', 'url' => ['/site/index']]
          //   :
          //   '',
              \Yii::$app->user->can('updateUser') && 
        !Yii::$app->user->isGuest ?  
            ['label'=>'users', 'url'=>['user/index']]

            :
            '',
           \Yii::$app->user->can('indexTeams') && 
        !Yii::$app->user->isGuest ?  
          ['label'=>'teams', 'url'=>['team/index']]
            :
            '',
                   \Yii::$app->user->can('indexPupil') && 
        !Yii::$app->user->isGuest ? 
            ['label'=>'pupils', 'url'=>['pupil/index']]
            :
            '',
                   \Yii::$app->user->can('indexActivity') && 
        !Yii::$app->user->isGuest ? 
            ['label'=>'activities', 'url'=>['activity/index']]
             :
            '',
                   \Yii::$app->user->can('indexActivity') && 
        !Yii::$app->user->isGuest ? 
            ['label'=>'events', 'url'=>['event/index']]
             :
            '',
         // !Yii::$app->user->isGuest ?
            // ['label'=>'reports', 'url'=>['reports/index']],
            //  :
            // '',
                      \Yii::$app->user->can('indexActivity') && 
        !Yii::$app->user->isGuest ? 
            ['label' => 'sticky notes', 'url' => ['/note']]
             :
            '',
         !Yii::$app->user->isGuest ?
              ['label' => 'about', 'url' => ['/site/about']]
              :
            '', 
            //   !Yii::$app->user->isGuest ?
            //     ['label' => 'Login', 'url' => ['/site/login']]
            //   :
            // '', 
                      Yii::$app->user->isGuest ? (
                        ''

                ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username .  ')',
                    ['class' => 'btn btn-link']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">

        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>
<!-- 
<footer class="footer">
    <div class="container">
       <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p> 
    </div>
</footer>
-->
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>